FROM node:16-slim

RUN mkdir -p /workspace/growi-ogp
RUN apt-get update \
    && apt-get install -y git python3 build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev fonts-noto-cjk
