version: '3'
services:
  node:
    user: node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/growi-ogp:delegated
      - node_modules:/workspace/growi-ogp/src/node_modules
    ports:
      - 8088:8088
    tty: true
volumes:
  node_modules:
