version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace/growi-ogp:delegated
    ports:
      - 8088:8088
    tty: true
    stdin_open: true
