name: ogp for growi
on: push

jobs:

  my_test:

    name: my test action
    runs-on: ubuntu-latest

    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: wsmoogle
          password: ${{ secrets.OGP_PAT }}
    
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            flavor=${{ matrix.flavor }}
          tags: latest